Multiclass classification

In [14]:
from sklearn.model_selection import train_test_split
import pandas as pd
df=pd.read_csv("/content/cars_fuel_efficiency_clean.csv")
df

,trip_id,car_name,vehicle_type,fuel_type,trip_category,distance_km,trip_duration_hr,avg_speed_kmph,base_mileage_kmpl,actual_mileage_kmpl,mileage_delta_kmpl,fuel_consumed_L,fuel_cost_usd,cost_per_km_usd,co2_emissions_kg,co2_per_km,relative_efficiency,efficiency_band
0,1,Lexus ES,Luxury,Diesel,Very Long (>400 km),437.85,4.84,90.51,11.31,11.24,-0.07,38.96,44.59,0.1018,104.413,0.2385,0.5979,Average
1,2,Lexus ES,Luxury,Petrol,Medium (50–200 km),181.86,3.54,51.43,9.98,9.61,-0.37,18.92,23.93,0.1316,43.705,0.2403,0.5113,Poor
2,3,Audi A6,Luxury,Petrol,Medium (50–200 km),118.07,1.46,80.62,11.06,11.24,0.18,10.50,13.28,0.1125,24.255,0.2054,0.5982,Average
3,4,Maruti Swift,Hatchback,Diesel,Long (200–400 km),343.16,4.72,72.65,21.17,19.65,-1.52,17.46,19.98,0.0582,46.793,0.1364,0.7181,Average
4,5,Hyundai Creta,SUV,Diesel,Long (200–400 km),371.03,3.87,95.78,13.01,12.39,-0.62,29.95,34.28,0.0924,80.266,0.2163,0.5717,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,596,Tata Tiago,Hatchback,Diesel,Medium (50–200 km),113.18,1.36,82.93,18.53,17.05,-1.48,6.64,7.60,0.0671,17.795,0.1572,0.6227,Average
596,597,Honda Brio,Hatchback,Diesel,Long (200–400 km),226.13,2.91,77.66,19.89,21.35,1.46,10.59,12.12,0.0536,28.381,0.1255,0.7801,Good
597,598,Audi A6,Luxury,Petrol,Medium (50–200 km),60.02,0.53,114.28,8.96,8.83,-0.13,6.80,8.60,0.1433,15.708,0.2617,0.4696,Poor
598,599,Maruti Swift,Hatchback,Diesel,Very Long (>400 km),414.00,7.03,58.91,21.65,20.97,-0.68,19.74,22.59,0.0546,52.903,0.1278,0.7662,Good
599,600,Tata Harrier,SUV,Petrol,Medium (50–200 km),188.31,2.68,70.14,11.84,11.76,-0.08,16.01,20.25,0.1075,36.983,0.1964,0.5428,Poor

In [11]:
X = df.drop(['efficiency_band', 'trip_id', 'car_name'], axis=1)
y = df['efficiency_band']

In [12]:
x=pd.get_dummies(X)

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [18]:
model.score(x_test,y_test)

0.65

In [19]:
model.predict(x_test)

array(['Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Good', 'Average', 'Good', 'Average', 'Poor',
       'Average', 'Average', 'Poor', 'Good', 'Good', 'Average', 'Good',
       'Good', 'Good', 'Good', 'Poor', 'Average', 'Average', 'Average',
       'Good', 'Good', 'Good', 'Good', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Good', 'Excellent', 'Average', 'Good', 'Average', 'Average',
       'Poor', 'Average', 'Average', 'Good', 'Average', 'Good', 'Poor',
       'Good', 'Average', 'Average', 'Good', 'Average', 'Average', 'Good',
       'Average', 'Average', 'Average', 'Good', 'Poor', 'Good', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Good', 'Average',
       'Average', 'Average', 'Average', 'Good', 'Average', 'Average',
       'Average', 'Good', 'Good', 'Average', 'Average', 'Good', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Good', 'Average', 'Good', 'Average', 'Average', 'Good', 'Average',
       'Poor', 'Average', 'Average'], dtype=object)

Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(random_state=42)
model.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [24]:
model.score(x_test,y_test)

1.0

In [25]:
model.predict(x_test)

array(['Average', 'Poor', 'Excellent', 'Average', 'Average', 'Average',
       'Good', 'Poor', 'Average', 'Poor', 'Average', 'Average', 'Average',
       'Good', 'Average', 'Poor', 'Excellent', 'Average', 'Poor',
       'Average', 'Average', 'Poor', 'Excellent', 'Good', 'Average',
       'Average', 'Average', 'Good', 'Average', 'Poor', 'Average', 'Good',
       'Average', 'Good', 'Good', 'Good', 'Good', 'Good', 'Average',
       'Good', 'Average', 'Average', 'Average', 'Average', 'Average',
       'Good', 'Average', 'Excellent', 'Average', 'Average', 'Average',
       'Good', 'Poor', 'Average', 'Average', 'Average', 'Average', 'Good',
       'Poor', 'Good', 'Average', 'Average', 'Average', 'Average',
       'Average', 'Good', 'Poor', 'Average', 'Average', 'Good', 'Poor',
       'Excellent', 'Average', 'Good', 'Average', 'Average', 'Average',
       'Average', 'Poor', 'Average', 'Average', 'Good', 'Good', 'Average',
       'Poor', 'Average', 'Good', 'Good', 'Good', 'Average', 'Average',
       'Average', 'Average', 'Good', 'Average', 'Average', 'Average',
       'Average', 'Average', 'Average', 'Average', 'Poor', 'Average',
       'Good', 'Average', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Excellent', 'Average', 'Excellent', 'Poor', 'Average',
       'Excellent', 'Average', 'Poor', 'Average', 'Average'], dtype=object)

In [ ]:
SVM

In [27]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
model=SVC()

In [33]:
model.fit(x_train,y_train)

SVC()

In [34]:
model.fit(x_train,y_train)

SVC()

In [35]:
model.score(x_test,y_test)

0.6333333333333333

Regularization

In [37]:
model_C=SVC(C=1)
model_C.fit(x_train,y_train)
model_C.score(x_test,y_test)

0.6333333333333333

Gamma

In [39]:
model_g=SVC(gamma=10)
model_g.fit(x_train,y_train)
model_g.score(x_test,y_test)

0.625

Kernel

In [41]:
model_linear_kernel=SVC(kernel='linear')
model_linear_kernel.fit(x_train,y_train)
model_linear_kernel.score(x_test,y_test)

0.8666666666666667

random_forest

In [43]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [44]:
model.score(x_test,y_test)

0.9833333333333333

KMeans

In [48]:
from sklearn.cluster import KMeans
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [50]:
model = KMeans(n_clusters=4, random_state=42)
model.fit(X_scaled)

df['cluster'] = model.labels_
df

,trip_id,car_name,vehicle_type,fuel_type,trip_category,distance_km,trip_duration_hr,avg_speed_kmph,base_mileage_kmpl,actual_mileage_kmpl,mileage_delta_kmpl,fuel_consumed_L,fuel_cost_usd,cost_per_km_usd,co2_emissions_kg,co2_per_km,relative_efficiency,efficiency_band,cluster
0,1,Lexus ES,Luxury,Diesel,Very Long (>400 km),437.85,4.84,90.51,11.31,11.24,-0.07,38.96,44.59,0.1018,104.413,0.2385,0.5979,Average,1
1,2,Lexus ES,Luxury,Petrol,Medium (50–200 km),181.86,3.54,51.43,9.98,9.61,-0.37,18.92,23.93,0.1316,43.705,0.2403,0.5113,Poor,1
2,3,Audi A6,Luxury,Petrol,Medium (50–200 km),118.07,1.46,80.62,11.06,11.24,0.18,10.50,13.28,0.1125,24.255,0.2054,0.5982,Average,2
3,4,Maruti Swift,Hatchback,Diesel,Long (200–400 km),343.16,4.72,72.65,21.17,19.65,-1.52,17.46,19.98,0.0582,46.793,0.1364,0.7181,Average,3
4,5,Hyundai Creta,SUV,Diesel,Long (200–400 km),371.03,3.87,95.78,13.01,12.39,-0.62,29.95,34.28,0.0924,80.266,0.2163,0.5717,Average,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,596,Tata Tiago,Hatchback,Diesel,Medium (50–200 km),113.18,1.36,82.93,18.53,17.05,-1.48,6.64,7.60,0.0671,17.795,0.1572,0.6227,Average,2
596,597,Honda Brio,Hatchback,Diesel,Long (200–400 km),226.13,2.91,77.66,19.89,21.35,1.46,10.59,12.12,0.0536,28.381,0.1255,0.7801,Good,3
597,598,Audi A6,Luxury,Petrol,Medium (50–200 km),60.02,0.53,114.28,8.96,8.83,-0.13,6.80,8.60,0.1433,15.708,0.2617,0.4696,Poor,2
598,599,Maruti Swift,Hatchback,Diesel,Very Long (>400 km),414.00,7.03,58.91,21.65,20.97,-0.68,19.74,22.59,0.0546,52.903,0.1278,0.7662,Good,3
599,600,Tata Harrier,SUV,Petrol,Medium (50–200 km),188.31,2.68,70.14,11.84,11.76,-0.08,16.01,20.25,0.1075,36.983,0.1964,0.5428,Poor,2

In [51]:
pd.crosstab(df['efficiency_band'], df['cluster'])

cluster           0    1    2   3
efficiency_band
Average          26  155  107  43
Excellent         3    1    7  33
Good             10   43   35  82
Poor              1   38   16   0

In [52]:
for k in range(2, 7):
    model = KMeans(n_clusters=k)
    model.fit(X_scaled)
    print(f"K={k}, Inertia={model.inertia_}")

K=2, Inertia=11589.526845284898
K=3, Inertia=10018.305500599883
K=4, Inertia=9159.997889984075
K=5, Inertia=8474.760360512833
K=6, Inertia=8107.621474372562